name: CI/CD for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Frontend Unit Tests
        working-directory: frontend
        run: npm test

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: backend
        run: npm test

  merge-to-main:
    needs: build-and-test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          title: "Merge dev into main"
          body: |
            Automatically merging changes from `dev` to `main`.
          commit-message: "chore: merge dev into main"
          delete-branch: false